services:
  - type: web
    name: zhongcao-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: MONGODB_URI
        sync: false